# Generated by Django 5.1.3 on 2024-11-21 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_alter_cuenta_cvu_alter_cuenta_tipo'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cuenta',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta'),
            preserve_default=False,
        ),
    ]
