# Generated by Django 5.1.3 on 2024-11-21 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_saldo_cliente_user_alter_cliente_dni_and_more'),
        ('cuentas', '0002_cuenta_numero_cuenta_alter_cuenta_saldo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo_cuenta',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cvu',
            field=models.CharField(default=False, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('BLACK', 'Black'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('CLASSIC', 'Classic')], default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
