# Generated by Django 5.1.3 on 2024-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_cuenta_saldo_alter_cuenta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
        ),
    ]
