# Generated by Django 5.1.3 on 2024-11-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_cuenta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cvu',
            field=models.CharField(default=None, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('BLACK', 'Black'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('CLASSIC', 'Classic')], default='CLASSIC', max_length=10),
        ),
    ]
