# Generated by Django 5.1.3 on 2024-11-19 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('tipo_tarjeta', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], default='DEBITO', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
