# Generated by Django 5.1.3 on 2024-11-20 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='tipo_tarjeta',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], default='DEBITO', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL),
        ),
    ]
